DROP TABLE ASKLYZE_AI_QUERY_STORE CASCADE CONSTRAINTS;
DROP TABLE ASKLYZE_CATALOG_COLUMNS CASCADE CONSTRAINTS;
DROP TABLE ASKLYZE_CATALOG_REFRESH_LOG CASCADE CONSTRAINTS;
DROP TABLE ASKLYZE_CATALOG_RELATIONS CASCADE CONSTRAINTS;
DROP TABLE ASKLYZE_CATALOG_SCHEMAS CASCADE CONSTRAINTS;
DROP TABLE ASKLYZE_CATALOG_TABLES CASCADE CONSTRAINTS;
DROP TABLE ASKLYZE_CATALOG_TABLE_ACCESS CASCADE CONSTRAINTS;
DROP TABLE ASKLYZE_CHART_TYPES CASCADE CONSTRAINTS;
DROP TABLE ASKLYZE_CLOUD_CONFIG CASCADE CONSTRAINTS;
DROP TABLE ASKLYZE_DASHBOARD_LAYOUTS CASCADE CONSTRAINTS;
DROP TABLE ASKLYZE_EXTERNAL_CONNECTIONS CASCADE CONSTRAINTS;

drop package ASKLYZE_CLOUD_CONNECTOR_PKG;
drop package ASKLYZE_UI_PKG;

